export type TarotCard = {
  id: number
  name: string
  nameEn: string
  emoji: string
  uprightKeywords: string[]
  reversedKeywords: string[]
  uprightMeaning: string
  reversedMeaning: string
}

export const TAROT_CARDS: TarotCard[] = [
  {
    id: 0,
    name: '愚者',
    nameEn: 'The Fool',
    emoji: '🃏',
    uprightKeywords: ['新しい始まり', '自由', '冒険', '無邪気'],
    reversedKeywords: ['無謀', '軽率', '現実逃避', '先が見えない'],
    uprightMeaning: '新しい旅の始まり。純粋な心で一歩を踏み出す時。可能性は無限大。',
    reversedMeaning: '準備不足や無謀な行動に注意。立ち止まって計画を見直す必要があるかも。',
  },
  {
    id: 1,
    name: '魔術師',
    nameEn: 'The Magician',
    emoji: '🪄',
    uprightKeywords: ['意志力', '創造力', 'スキル', '行動力'],
    reversedKeywords: ['詐欺', '才能の無駄遣い', '自信過剰', '操作'],
    uprightMeaning: '必要なものはすべて揃っている。行動に移す絶好のタイミング。',
    reversedMeaning: '才能を活かせていないか、誰かに操られている可能性。',
  },
  {
    id: 2,
    name: '女教皇',
    nameEn: 'The High Priestess',
    emoji: '🌙',
    uprightKeywords: ['直感', '内なる声', '神秘', '知恵'],
    reversedKeywords: ['秘密', '直感の無視', '混乱', '内向きすぎ'],
    uprightMeaning: '内なる声に耳を傾けて。答えはすでにあなたの中にある。',
    reversedMeaning: '直感を無視している状態。隠されている情報があるかもしれない。',
  },
  {
    id: 3,
    name: '女帝',
    nameEn: 'The Empress',
    emoji: '👑',
    uprightKeywords: ['豊かさ', '育み', '美', '自然'],
    reversedKeywords: ['依存', '過保護', '創造性の欠如', '停滞'],
    uprightMeaning: '豊かさと創造の時期。愛情に満ちた環境で物事が花開く。',
    reversedMeaning: '依存関係や過保護に注意。自立することが大切な時。',
  },
  {
    id: 4,
    name: '皇帝',
    nameEn: 'The Emperor',
    emoji: '⚔️',
    uprightKeywords: ['権威', '安定', '構造', 'リーダーシップ'],
    reversedKeywords: ['支配', '頑固', '独裁', '柔軟性不足'],
    uprightMeaning: '強い基盤と安定をもたらす。リーダーシップを発揮する時。',
    reversedMeaning: '支配的な力や権威との衝突。柔軟性を持つことが必要。',
  },
  {
    id: 5,
    name: '教皇',
    nameEn: 'The Hierophant',
    emoji: '⛪',
    uprightKeywords: ['伝統', '信仰', '教え', '精神的指導'],
    reversedKeywords: ['因習打破', '束縛', '非正統', '反抗'],
    uprightMeaning: '伝統や信頼できる教えに従う時。精神的な指導者を求めるとよい。',
    reversedMeaning: '古い価値観を疑う時期。自分だけの道を切り開く必要があるかも。',
  },
  {
    id: 6,
    name: '恋人',
    nameEn: 'The Lovers',
    emoji: '💕',
    uprightKeywords: ['愛', '選択', '調和', 'パートナーシップ'],
    reversedKeywords: ['不一致', '誘惑', '優柔不断', '価値観の対立'],
    uprightMeaning: '重要な選択の時。愛と調和が導く決断。関係の深まりを示す。',
    reversedMeaning: '価値観のズレや誘惑に注意。大切なことを見極める必要がある。',
  },
  {
    id: 7,
    name: '戦車',
    nameEn: 'The Chariot',
    emoji: '🏆',
    uprightKeywords: ['勝利', '意志力', '前進', '自制心'],
    reversedKeywords: ['暴走', '自制心の欠如', '方向性の迷い', '敗北'],
    uprightMeaning: '強い意志で勝利をつかむ時。前進あるのみ。目標に向かって突き進め。',
    reversedMeaning: '方向性を失っているか暴走しがち。一度立ち止まってリセットを。',
  },
  {
    id: 8,
    name: '力',
    nameEn: 'Strength',
    emoji: '🦁',
    uprightKeywords: ['内なる強さ', '勇気', '忍耐', '情熱'],
    reversedKeywords: ['自信喪失', '弱さ', '自己疑念', '感情の爆発'],
    uprightMeaning: '柔らかさの中に宿る真の強さ。勇気と忍耐で乗り越えられる。',
    reversedMeaning: '自信を失っている状態。自分を信じることが力を取り戻す鍵。',
  },
  {
    id: 9,
    name: '隠者',
    nameEn: 'The Hermit',
    emoji: '🕯️',
    uprightKeywords: ['内省', '孤独', '探求', '知恵'],
    reversedKeywords: ['孤立', '引きこもり', '頑固', '内省のしすぎ'],
    uprightMeaning: '一人で静かに内省する時。答えは内側にある。ゆっくり進んでよい。',
    reversedMeaning: '孤立しすぎているか、変化を恐れている。外の世界に目を向けて。',
  },
  {
    id: 10,
    name: '運命の輪',
    nameEn: 'Wheel of Fortune',
    emoji: '🎡',
    uprightKeywords: ['転換点', '運命', '幸運', 'サイクル'],
    reversedKeywords: ['不運', '抵抗', '変化への恐れ', 'サイクルの乱れ'],
    uprightMeaning: '人生の転換点。運命の歯車が動き出す。変化を受け入れると吉。',
    reversedMeaning: '変化への抵抗が不運を招いている。流れに乗ることが大切。',
  },
  {
    id: 11,
    name: '正義',
    nameEn: 'Justice',
    emoji: '⚖️',
    uprightKeywords: ['公正', '真実', '法', '均衡'],
    reversedKeywords: ['不公正', '不誠実', '偏見', '責任回避'],
    uprightMeaning: '公正な結果が訪れる。誠実に行動すれば正当な評価を受ける。',
    reversedMeaning: '不公平な状況や責任逃れに注意。誠実さが問われている。',
  },
  {
    id: 12,
    name: '吊された男',
    nameEn: 'The Hanged Man',
    emoji: '🔮',
    uprightKeywords: ['待機', '視点の転換', '犠牲', '悟り'],
    reversedKeywords: ['停滞', '無駄な犠牲', '遅延', '頑固'],
    uprightMeaning: '今は待つ時。別の視点から物事を見ることで新たな悟りが開ける。',
    reversedMeaning: '無駄な抵抗や停滞。手放すことで前に進める。',
  },
  {
    id: 13,
    name: '死神',
    nameEn: 'Death',
    emoji: '🌹',
    uprightKeywords: ['終わりと始まり', '変容', '手放し', '再生'],
    reversedKeywords: ['変化への抵抗', '停滞', '過去への執着', '恐れ'],
    uprightMeaning: '終わりは始まりの象徴。何かを手放すことで新しい扉が開く。',
    reversedMeaning: '過去に執着して前に進めない状態。変化を受け入れる勇気を。',
  },
  {
    id: 14,
    name: '節制',
    nameEn: 'Temperance',
    emoji: '✨',
    uprightKeywords: ['バランス', '調和', '忍耐', '癒し'],
    reversedKeywords: ['不均衡', '過剰', '不調和', '焦り'],
    uprightMeaning: 'バランスと調和が鍵。焦らず着実に。癒しと再生のエネルギーがある。',
    reversedMeaning: '何かが極端になっている。バランスを取り戻すことが急務。',
  },
  {
    id: 15,
    name: '悪魔',
    nameEn: 'The Devil',
    emoji: '🖤',
    uprightKeywords: ['束縛', '誘惑', '依存', '物質主義'],
    reversedKeywords: ['解放', '束縛からの脱出', '自由', '覚醒'],
    uprightMeaning: '何かに縛られている感覚。しかしその鎖は自分で外せるもの。',
    reversedMeaning: '束縛からの解放が近い。依存や恐れを手放す絶好のチャンス。',
  },
  {
    id: 16,
    name: '塔',
    nameEn: 'The Tower',
    emoji: '⚡',
    uprightKeywords: ['突然の変化', '崩壊', '啓示', '混乱'],
    reversedKeywords: ['変化の先延ばし', '災難回避', '内的混乱', '恐れ'],
    uprightMeaning: '突然の変化や崩壊。しかしそれは古いものを取り除き新しい未来への道。',
    reversedMeaning: '変化を避けようとしている。内側から崩れている可能性も。',
  },
  {
    id: 17,
    name: '星',
    nameEn: 'The Star',
    emoji: '⭐',
    uprightKeywords: ['希望', '癒し', '信頼', 'インスピレーション'],
    reversedKeywords: ['絶望', '不信', '失望', '自信喪失'],
    uprightMeaning: '希望と癒しの光が差し込む。信じて進めば夢は叶う。輝く未来が待っている。',
    reversedMeaning: '希望を失いそうになっている。しかし星の光は消えていない。',
  },
  {
    id: 18,
    name: '月',
    nameEn: 'The Moon',
    emoji: '🌕',
    uprightKeywords: ['幻想', '不安', '潜在意識', '直感'],
    reversedKeywords: ['混乱の解消', '真実の発覚', '恐れの克服', '明確さ'],
    uprightMeaning: '見えないものへの不安。しかし直感に従えば迷いの霧が晴れていく。',
    reversedMeaning: '長く続いた混乱や幻想から解放される時。真実が明らかに。',
  },
  {
    id: 19,
    name: '太陽',
    nameEn: 'The Sun',
    emoji: '☀️',
    uprightKeywords: ['喜び', '成功', '活力', '明るさ'],
    reversedKeywords: ['過信', '悲観', '一時的な曇り', '喜びの遅延'],
    uprightMeaning: '最高の吉兆。喜びと成功に満ちた時期。すべてがうまくいく輝かしい未来。',
    reversedMeaning: '一時的な曇り空。しかし太陽は必ず戻ってくる。楽観的に。',
  },
  {
    id: 20,
    name: '審判',
    nameEn: 'Judgement',
    emoji: '🎺',
    uprightKeywords: ['再生', '覚醒', '評価', '呼びかけ'],
    reversedKeywords: ['自己批判', '決断の遅れ', '後悔', '内なる声の無視'],
    uprightMeaning: '新たな覚醒と再生の時。内なる呼びかけに答えて高い次元に進む。',
    reversedMeaning: '過去の後悔に縛られている。自分を許し前に進む時が来ている。',
  },
  {
    id: 21,
    name: '世界',
    nameEn: 'The World',
    emoji: '🌍',
    uprightKeywords: ['完成', '達成', '統合', '旅の終わり'],
    reversedKeywords: ['未完成', '停滞', '閉塞感', '惜しいところ'],
    uprightMeaning: '完全な達成と完成。一つの旅が終わり、また新たな旅へ。最高の結果が待っている。',
    reversedMeaning: 'もう少しで完成なのに止まっている。最後の一歩を踏み出して。',
  },
]

export function drawCard(): { card: TarotCard; isReversed: boolean } {
  const card = TAROT_CARDS[Math.floor(Math.random() * TAROT_CARDS.length)]
  const isReversed = Math.random() < 0.5
  return { card, isReversed }
}
